; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

#the board model only allow qio(4 ways) connection
board_build.arduino.memory_type = qio_opi 
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv

monitor_speed = 115200

build_flags = 
    -DBOARD_HAS_PSRAM
    -D ESP_PLATFORM
    -D EI_CLASSIFIER_TFLITE_ENABLE_ESP_NN=1
    -I lib/model_v5/src/edge-impulse-sdk/porting/espressif/ESP-NN/include
    -I lib/model_v5/src


lib_ldf_mode = deep+

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    https://github.com/alanswx/ESPAsyncWiFiManager.git
    https://github.com/esphome/ESPAsyncWebServer.git #solve enum conflicts
    bitbank2/JPEGDEC @ ^1.2.8
    