; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino



; MUDANÇA AQUI: qio para Flash (4 vias) e opi para PSRAM (8 vias)
board_build.arduino.memory_type = qio_opi 
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv

monitor_speed = 115200

build_flags = 
    -DBOARD_HAS_PSRAM 
        ; Correção de bugs de cache do S3
lib_ldf_mode = deep+

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    https://github.com/alanswx/ESPAsyncWiFiManager.git
    https://github.com/esphome/ESPAsyncWebServer.git #solve enum conflicts
    bitbank2/JPEGDEC @ ^1.2.8
    